server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml

spring:
  messages:
    cache-duration: 1h

logging:
  level:
    ROOT: INFO
    io.github.susimsek.springbootgraalvmnativeexample: INFO
  async:
    queueSize: 10000
    discardingThreshold: 0
    maxFlushTime: 5000
    includeCallerData: false
