apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graalvm-native-app.fullname" . | quote }}
  namespace: {{ include "graalvm-native-app.namespace" . | quote }}
  labels: {{- include "graalvm-native-app.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: graalvm-native-app
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "graalvm-native-app.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  SERVER_PORT: {{ .Values.spring.server.port | quote }}
